pr: none
trigger: none

variables:
  dockerContainerName: discord-hof-dab
  dockerContainerPort: 14778

stages:
  - stage: deployDab
    displayName: Deploy
    jobs:
      - deployment: deployDab
        pool: prod-vm-uks-core
        environment: dab
        variables:
          - group: deploy-dab
        strategy:
          runOnce:
            deploy:
              steps:
                - script: docker pull mcr.microsoft.com/azure-databases/data-api-builder:latest
                  displayName: Pull image

                - script: docker rm -f $(dockerContainerName)
                  displayName: Remove existing container

                - script: |
                    docker run -d \
                      --name $(dockerContainerName) \
                      --restart always \
                      -p $(dockerContainerPort):5000 \
                      -e DATABASE_CONNECTION_STRING \
                      -v /var/discord-hof-dab.config.json:/cfg/dab-config.json:ro \
                      mcr.microsoft.com/azure-databases/data-api-builder:latest \
                      dotnet Azure.DataApiBuilder.Service.dll --ConfigFileName /cfg/dab-config.json
                  displayName: Start container
                  env:
                    DATABASE_CONNECTION_STRING: $(DATABASE_CONNECTION_STRING)
